# Generated by Django 5.0.4 on 2024-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_price', models.IntegerField(blank=True, null=True)),
                ('P_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='Product Main Images')),
            ],
        ),
    ]
